clc;
close all;
clear;
R = 1000;
L = 3.18;
f = 50;
Vrms = 220;
XL = 2 * pi * f * L;
Z = sqrt(R^2 + XL^2);
theta_rad = atan(XL / R);
theta_deg = theta_rad*(180/pi);
fprintf("Phase angle: %.2f\n", theta_deg);
Vp = sqrt(2) * Vrms;
Ip = Vp / Z;
T = 1 / f;
t = linspace(0, 2*T, 1000);
omega = 2 * pi * f;
v = Vp * sin(omega * t);
i = Ip * sin(omega * t - theta_rad);
subplot(2,1,1);
plot(t, v, 'b');
title('Input Voltage vs Time');
xlabel('Time(s)');
ylabel('Voltage(V)');
grid on;

subplot(2,1,2);
plot(t, i, 'r');
title('Current vs Time');
xlabel('Time (s)');
ylabel('Current (A)');
grid on;